# Backup cron
MARIADB_BACKUP_CRON_EXP: 0 4 * * * #every day at 4:00am
MARIADB_BACKUP_TTL: 15 # Delete backups that are over 15 days

# ssl
MARIADB_SSL: true
MARIADB_SSL_CIPHER_SUITE: TLSv1.2

MARIADB_SSL_CRT_FILENAME: mariadb.crt
MARIADB_SSL_KEY_FILENAME: mariadb.key
MARIADB_SSL_CA_CRT_FILENAME: ca.crt
