#!/bin/bash -e

# Usage: /sbin/mariadb-backup

source /etc/container_environment.sh

backupPath="/data/backup"

dateFileFormat="+%F-%T"
newBackupPath="$backupPath/$(date "$dateFileFormat")"

innobackupex --user=$MARIADB_BACKUP_USER  --password=$MARIADB_BACKUP_PASSWORD --no-timestamp $newBackupPath

innobackupex --apply-log $newBackupPath
