#!/bin/bash -e

# Usage: /sbin/mariadb-backup

source /container/run/environment.sh

backupPath="/data/backup"

# delete backups that are over $MARIADB_BACKUP_TTL days
find $backupPath -type f -mtime +$MARIADB_BACKUP_TTL -exec rm {} \;

dateFileFormat="+%Y%m%dT%H%M%S"
newBackupPath="$backupPath/$(date "$dateFileFormat")"

innobackupex --compress --user=$MARIADB_BACKUP_USER  --password=$MARIADB_BACKUP_PASSWORD --no-timestamp $newBackupPath

chmod 600 -R $newBackupPath

exit 0
